const os = require("os")
console.log(os.freemem())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.platform())
console.log(os.release())
//console.log(os.EOL())
console.log(os.availableParallelism())
console.log(os.type())
console.log(os.getPriority())
console.log(os.machine())